### ISSUE TITLE
不填写名称，可点击创建指定共享文件夹

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/fruitmix-android#276]
测试步骤：
1.连接设备登录账户；
2.进入共享文件夹页，点击浮动图标新建指定共享文件夹；
3.勾选用户权限后，不填写名称，点击创建。

当前结果：
不填写名称，点击创建，能够进行指定共享文件夹创建，但报网络错误400

**Comment by andywu91** [comment]
修改为名称不能为空
