### ISSUE TITLE
指定共享盘创建者权限不能被取消

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/fruitmix-android#277]
### 测试步骤：
1.连接设备登录账户；
2.进入共享文件夹页，创建指定共享文件夹后，点击文件夹后【更多】选项进入权限设置；
3.取消所有用户权限（包括该文件夹创建者）；
4.刷新页面查看。

### 当前结果：
创建者权限未被取消。

**Comment by andywu91** [comment]
管理员作为创建者，修改为禁止取消权限，
