### ISSUE TITLE
手机端已下载文件删除出现网络错误

### ISSUE THREAD

**Issue by trevorwang12** [wisnuc/fruitmix-android#51]
已经下载的到手机端本地的照片，用手机端删除不掉，报网络错误。
![image](https://user-images.githubusercontent.com/20084315/30154993-3da0fdae-93ee-11e7-8fdb-e6ef8e3ca82a.png)

**Comment by andywu91** [comment]
同bug#44

**Comment by flugwang** [comment]
已调整菜单缺陷
