### ISSUE TITLE
取消照片勾选，显示失误

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/fruitmix-android#59]
测试步骤：
登录wisnuc，选择模式下选择照片，下滑查看更多照片
退出选择模式，返回选中照片的时间段

当前结果：
当页面滑动至被选中图片时，选择状态下的勾选图标高亮，随后消失。

**Comment by andywu91** [comment]
退出选择模式，不会即时刷新所有图片，滑动到选中图片时，才会更新控件状态
